### ISSUE TITLE
老哥,格式化的时候能不能把%{  }% 之间的代码加上空格? 看着好难受..

### ISSUE THREAD

**Issue by csdjk** [x1phyr/cocos-effect-formatter#1]
![image](https://github.com/x1phyr/cocos-effect-formatter/assets/33519787/ef63a938-6d12-4739-b030-f76b5694ccd8)

**Comment by x1phyr** [comment]
![image](https://github.com/user-attachments/assets/40961e6f-60ee-4caf-8556-5a688f7a6574)
抱歉，没看到消息，加了个开关，应该能满足你的要求。
